apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  project: demo-project          # ðŸ‘ˆ ArgoCD Project

  source:
    repoURL: https://github.com/RamitTechnical/argocd-demos.git
    targetRevision: main
    path: kubernetes_file
  destination:
    server: https://kubernetes.default.svc
    namespace: demo               # ðŸ‘ˆ Kubernetes namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
